export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const ALL_MANUFACTURERS = 'ALL_MANUFACTURERS'
export const MANUFACTURER_BY_ID = 'MANUFACTURER_BY_ID'
export const ADD_MANUFACTURER = 'ADD_MANUFACTURER'
export const UPDATE_MANUFACTURER = 'UPDATE_MANUFACTURER'
export const REMOVE_MANUFACTURER = 'REMOVE_MANUFACTURER'

export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

export const ALL_USERS = 'ALL_USERS'
export const USER_BY_ID = 'USER_BY_ID'
export const ADD_USER = 'ADD_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

